//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares {
    
    
    public partial class IzbiraPredmetovReferent2 {
        
        /// <summary>
        /// spremeniPredmetnik control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spremeniPredmetnik;
        
        /// <summary>
        /// feedbackLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label feedbackLB;
        
        /// <summary>
        /// seznamPredmetovGV control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView seznamPredmetovGV;
        
        /// <summary>
        /// sestevekKreditnihTockLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label sestevekKreditnihTockLB;
        
        /// <summary>
        /// novPredmetDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl novPredmetDiv;
        
        /// <summary>
        /// dodajProstoIzbirniPredmetDDL_3kt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList dodajProstoIzbirniPredmetDDL_3kt;
        
        /// <summary>
        /// dodajProstoIzbirniPredmetBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button dodajProstoIzbirniPredmetBtn;
        
        /// <summary>
        /// dodajProstoIzbirniPredmetErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label dodajProstoIzbirniPredmetErrorLB;
        
        /// <summary>
        /// spremeniPredmet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl spremeniPredmet;
        
        /// <summary>
        /// spremeniPredmetInfoLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label spremeniPredmetInfoLB;
        
        /// <summary>
        /// spremeniPredmetSeznamOpcijDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList spremeniPredmetSeznamOpcijDDL;
        
        /// <summary>
        /// potrdiSpremeniPredmet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button potrdiSpremeniPredmet;
        
        /// <summary>
        /// zavrziSpremeniPredmet control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button zavrziSpremeniPredmet;
        
        /// <summary>
        /// potrdiSpremeniPredmetErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label potrdiSpremeniPredmetErrorLB;
        
        /// <summary>
        /// novPredmetnik control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl novPredmetnik;
        
        /// <summary>
        /// drugiLetnikDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl drugiLetnikDiv;
        
        /// <summary>
        /// drugiStrokovniIzbirniDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList drugiStrokovniIzbirniDDL;
        
        /// <summary>
        /// drugiStrokovniIzbirniErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label drugiStrokovniIzbirniErrorLB;
        
        /// <summary>
        /// drugiProstoIzbirniDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList drugiProstoIzbirniDDL;
        
        /// <summary>
        /// drugiProstoIzbirniErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label drugiProstoIzbirniErrorLB;
        
        /// <summary>
        /// drugiProstoIzbirniLB_3kt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label drugiProstoIzbirniLB_3kt;
        
        /// <summary>
        /// drugiProstoIzbirniDDL_3kt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList drugiProstoIzbirniDDL_3kt;
        
        /// <summary>
        /// drugiProstoIzbirni_3kt_ErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label drugiProstoIzbirni_3kt_ErrorLB;
        
        /// <summary>
        /// potrdiDrugiButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button potrdiDrugiButton;
        
        /// <summary>
        /// tretjiLetnikDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tretjiLetnikDiv;
        
        /// <summary>
        /// tretjiPrviModulDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList tretjiPrviModulDDL;
        
        /// <summary>
        /// tretjiPrviModulErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label tretjiPrviModulErrorLB;
        
        /// <summary>
        /// tretjiDrugiModulDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList tretjiDrugiModulDDL;
        
        /// <summary>
        /// tretjiDrugiModulErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label tretjiDrugiModulErrorLB;
        
        /// <summary>
        /// tretjiProstoIzbirniDDL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList tretjiProstoIzbirniDDL;
        
        /// <summary>
        /// tretjiProstoIzbirniErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label tretjiProstoIzbirniErrorLB;
        
        /// <summary>
        /// tretjiProstoIzbirniLB_3kt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label tretjiProstoIzbirniLB_3kt;
        
        /// <summary>
        /// tretjiProstoIzbirniDDL_3kt control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList tretjiProstoIzbirniDDL_3kt;
        
        /// <summary>
        /// tretjiProstoIzbirni_3kt_ErrorLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label tretjiProstoIzbirni_3kt_ErrorLB;
        
        /// <summary>
        /// potrdiTretjiButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button potrdiTretjiButton;
        
        /// <summary>
        /// tretjiLetnikPovprecjeDiv control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl tretjiLetnikPovprecjeDiv;
        
        /// <summary>
        /// tretjiPovprecjeCBL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBoxList tretjiPovprecjeCBL;
        
        /// <summary>
        /// kTockeLB control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label kTockeLB;
        
        /// <summary>
        /// potrdiTretjiPovprecjeButton control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button potrdiTretjiPovprecjeButton;
    }
}
