-- FRI UNI dodiplomski -->
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63277,"Programiranje 1");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63202,"Osnove matematične analize");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63203,"Diskretne strukture");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63204,"Osnove digitalnih vezij");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63205,"Fizika");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63278,"Programiranje 2");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63207,"Linearna algebra");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63208,"Osnove podatkovnih baz");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63209,"Računalniške komunikacije");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63210,"Komunikacija človek računalnik");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63279,"Algoritmi in podatkovne strukture 1");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63212,"Arhitektura računalniških sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63213,"Verjetnost in statistika");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63280,"Algoritmi in podatkovne strukture 2");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63215,"Osnove informacijskih sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63216,"Teorija informacij in sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63217,"Operacijski sistemi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63218,"Organizacija računalniških sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63219,"Matematično modeliranje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63220,"Principi programskih jezikov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63221,"Računalniške tehnologije");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63246,"Komuniciranje in vodenje projektov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63248,"Ekonomika in podjetništvo");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63249,"Elektronsko poslovanje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63251,"Poslovna inteligenca");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63250,"Organizacija in management");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63252,"Razvoj informacijskih sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63226,"Tehnologija upravljanja podatkov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63253,"Planiranje in upravljanje informatike");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63254,"Postopki razvoja programske opreme");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63255,"Spletno programiranje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63256,"Tehnologija programske opreme");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63257,"Modeliranje računalniških omrežij");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63258,"Komunikacijski protokoli");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63259,"Brezžična in mobilna omrežja");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63260,"Digitalno načrtovanje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63261,"Poraydeljeni sistemi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63262,"Zanesljivost in zmogljivost računalniških sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63263,"Računska zahtevnost in hevristično programiranje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63264,"Sistemska programska oprema");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63265,"Prevajalniki");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63266,"Inteligentni sistemi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63267,"Umetno zaznavanje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63268,"Razvoj inteligentnih sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63269,"Računalniška grafika in tehnologija iger");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63270,"Multimedijski sistemi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63271,"Osnove oblikovanja");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63222,"Angleški jezik nivo A");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63223,"Angleški jezik nivo B");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63224,"Angleški jezik nivo C");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63225,"Izbrana poglavja iz računalništva in informatike - Analiza omrežij");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63241,"Računalništvo v praksi I");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63242,"Računalništvo v praksi II");
-- FRI VSŠ dodiplomski
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63701,"Uvod v računalništvo");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63702,"Programiranje 1");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63703,"Računalniška arhitektura");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63704,"Matematika");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63705,"Diskretne strukture");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63706,"Programiranje 2");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63707,"Podatkovne baze");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63708,"Računalniške komunikacije");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63709,"Operacijski sistemi");
-- FRI VSŠ strokovni izbirni predmeti 2.letnik VSŠ
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63711,"Algoritmi in podatkovne strukture 1");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63712,"Elektronsko in mobilno poslovanje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63713,"Podatkovne baze 2");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63714,"Informacijski sistemi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63715,"Grafično oblikovanje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63716,"Komunikacijski protokoli in omrežna varnost");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63717,"Organizacija računalnikov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63718,"Digitalna veyja");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63719,"Računalniška grafika");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63720,"Umetna inteligenca");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63721,"Uporabniški vmesniki");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63723,"Algoritmi in podatkovne strukture 2");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63722,"Prevajalnik in navidezni stroji");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63724,"Testiranje in kakovost");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63725,"Razvoj informacijskih sistemov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63726,"Produkcija multimedijskih gradiv");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63744,"Digitalno procesiranje signalov");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63727,"Spletne tehnologije");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63728,"Vhodno izhodne naprave");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63729,"Načrtovanje digitalnih naprav");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63765,"Podatkovno rudarjenje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63754,"Izvedbe algoritmov (Razvoj sistemov na čipu v jeziku Verilog)");
-- FRI VSŠ splošno 3.letnik VSŠ
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63755,"Projektni praktikum");
-- FRI VSŠ strokovni izbirni predmeti 3.letnik VSŠ dodiplomski
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63732,"Tehnologija programske opreme");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63733,"Strateško planiranje informatike");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63734,"Multimedijske tehnologije");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63735,"Vzporedni in porazdeljeni sistemi in algoritmi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63736,"Sistemska programska oprema");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63737,"Procesna avtomatika");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63738,"Vgrajeni sistemi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63739,"Robotika in računalniško zaznavanje");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63740,"Tehnologija iger in navidezna resničnost");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63741,"Odločitveni sistemi");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63742,"Numerične metode");
-- FRI VSŠ prosto izbirni predmeti VSŠ dodiplomski
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63745,"Angleški jezik nivo A");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63746,"Angleški jezik nivo B");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63747,"Angleški jezik nivo C");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63748,"Ekonomika in organizacija informatike");
-- INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63749A,"Izbrana poglavja iz računalništva in informatike (Houdini fx:osnove proceduralnega modeliranja)");
-- INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63749B,"Izbrana poglavja iz računalništva in informatike (Upravljanje tehnoloških podjetij)");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63752,"Računalništvo v praksi I");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63753,"Računalništvo v praksi II");
INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63750,"Športna vzgoja");
-- INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63764A,"Računalniška orodja, jeziki in okolja - TP A (Programski jezik C)");
-- INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(63764B,"Računalniška orodja, jeziki in okolja - TP B (Gradnja Oblakov z ogrodjem OpenStack)");
-- INSERT INTO `t8_2015`.`Predmet`(`idPredmet`,`imePredmeta`)VALUES(,"");
