INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Marko","Bajec");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Ivan","Bratko");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Franc","Jager");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Matjaž","Branko Jurič");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Aleksandar","Jurišić");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Igor","Kononenko");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Aleš","Leonardis");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Neža","Mramor Kosta");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Miha","Mraz");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Bojan","Orel");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Borut","Robič");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Franc","Solina");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Branko","Šter");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Denis","Trček");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Nikolaj","Zimic");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Blaž","Zupan");
-- izredni profesorji
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Zoran","Bosnić");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Patricio","Bulić");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Janez","Demšar");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Gašper","Fijavž");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Uroš","Lotrič");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Viljan","Mahnič");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Polona","Oblak");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Peter","Peer");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Fabio","Ricciato");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Marko","Robnik-Šikonja");
-- docenti
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Narvika","Bovcon");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Andrej","Brodnik");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Tomaž","Curk");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Matej","Kristan");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Matjaž","Kukar");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Iztok","Lebar Bajec");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Matija","Marolt");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Veljko","Pejović");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Rok","Rupnik");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Danijel","Skočaj");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Boštjan","Slivnik");
INSERT INTO `t8_2015`.`Profesor`(`imeProfesorja`,`priimekProfesorja`)VALUES("Mira","Trebar");