//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drzava
    {
        public Drzava()
        {
            this.Student = new HashSet<Student>();
            this.Student1 = new HashSet<Student>();
            this.Student2 = new HashSet<Student>();
            this.Student3 = new HashSet<Student>();
        }
    
        public int idDrzava { get; set; }
        public string imeDrzave { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
        public virtual ICollection<Student> Student1 { get; set; }
        public virtual ICollection<Student> Student2 { get; set; }
        public virtual ICollection<Student> Student3 { get; set; }
    }
}
