//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class IzvedbaPredmeta
    {
        public IzvedbaPredmeta()
        {
            this.IzpitniRok = new HashSet<IzpitniRok>();
            this.VpisaniPredmet = new HashSet<VpisaniPredmet>();
        }
    
        public int idIzvedbaPredmeta { get; set; }
        public int Profesor_idProfesor { get; set; }
        public Nullable<int> Profesor_idProfesor1 { get; set; }
        public Nullable<int> Profesor_idProfesor2 { get; set; }
        public int StudijskoLeto_idStudijskoLeto { get; set; }
        public int PredmetStudijskegaPrograma_PredmetStudijskegaProgramaId { get; set; }
    
        public virtual ICollection<IzpitniRok> IzpitniRok { get; set; }
        public virtual PredmetStudijskegaPrograma PredmetStudijskegaPrograma { get; set; }
        public virtual Profesor Profesor { get; set; }
        public virtual Profesor Profesor1 { get; set; }
        public virtual Profesor Profesor2 { get; set; }
        public virtual StudijskoLeto StudijskoLeto { get; set; }
        public virtual ICollection<VpisaniPredmet> VpisaniPredmet { get; set; }
    }
}
