//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Letnik
    {
        public Letnik()
        {
            this.PredmetStudijskegaPrograma = new HashSet<PredmetStudijskegaPrograma>();
            this.Vpis = new HashSet<Vpis>();
        }
    
        public int idLetnik { get; set; }
        public Nullable<int> letnik1 { get; set; }
    
        public virtual ICollection<PredmetStudijskegaPrograma> PredmetStudijskegaPrograma { get; set; }
        public virtual ICollection<Vpis> Vpis { get; set; }
    }
}
