//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class NacinStudija
    {
        public NacinStudija()
        {
            this.Vpis = new HashSet<Vpis>();
        }
    
        public int idNacinStudija { get; set; }
        public string opisNacina { get; set; }
        public string engOpisNacina { get; set; }
    
        public virtual ICollection<Vpis> Vpis { get; set; }
    }
}
