//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class t8_2015Entities11 : DbContext
    {
        public t8_2015Entities11()
            : base("name=t8_2015Entities11")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Drzava> Drzava { get; set; }
        public virtual DbSet<IzpitniRok> IzpitniRok { get; set; }
        public virtual DbSet<IzvedbaPredmeta> IzvedbaPredmeta { get; set; }
        public virtual DbSet<Klasius> Klasius { get; set; }
        public virtual DbSet<Letnik> Letnik { get; set; }
        public virtual DbSet<NacinStudija> NacinStudija { get; set; }
        public virtual DbSet<Obcina> Obcina { get; set; }
        public virtual DbSet<OblikaStudija> OblikaStudija { get; set; }
        public virtual DbSet<Posta> Posta { get; set; }
        public virtual DbSet<Predmet> Predmet { get; set; }
        public virtual DbSet<PredmetStudijskegaPrograma> PredmetStudijskegaPrograma { get; set; }
        public virtual DbSet<Prijava> Prijava { get; set; }
        public virtual DbSet<PrijavaNaIzpit> PrijavaNaIzpit { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
        public virtual DbSet<SestavniDelPred> SestavniDelPred { get; set; }
        public virtual DbSet<Sklep> Sklep { get; set; }
        public virtual DbSet<StatusPrijave> StatusPrijave { get; set; }
        public virtual DbSet<stopnjaStudija> stopnjaStudija { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudijskiProgram> StudijskiProgram { get; set; }
        public virtual DbSet<StudijskoLeto> StudijskoLeto { get; set; }
        public virtual DbSet<Vloge> Vloge { get; set; }
        public virtual DbSet<Vpis> Vpis { get; set; }
        public virtual DbSet<VpisaniPredmet> VpisaniPredmet { get; set; }
        public virtual DbSet<VrstaVpisa> VrstaVpisa { get; set; }
        public virtual DbSet<Zeton> Zeton { get; set; }
    }
}
