//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class OblikaStudija
    {
        public OblikaStudija()
        {
            this.Vpis = new HashSet<Vpis>();
        }
    
        public int idOblikaStudija { get; set; }
        public string opisOblike { get; set; }
        public string engOpisOblike { get; set; }
    
        public virtual ICollection<Vpis> Vpis { get; set; }
    }
}
