//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrijavaNaIzpit
    {
        public int idPrijavaNaizpit { get; set; }
        public Nullable<System.DateTime> DatumPrijave { get; set; }
        public Nullable<System.DateTime> DatumSpremembe { get; set; }
        public Nullable<int> IzpitniRok_IdIzpitniRok { get; set; }
        public Nullable<int> VpisaniPredmet_IdVpisanipredmet { get; set; }
        public Nullable<int> StatusPrijaveNaIzpit_IdStatusPrijaveNaIzpit { get; set; }
        public Nullable<int> OcenaIzpita { get; set; }
        public Nullable<int> StTock { get; set; }
    
        public virtual IzpitniRok IzpitniRok { get; set; }
        public virtual StatusPrijave StatusPrijave { get; set; }
        public virtual VpisaniPredmet VpisaniPredmet { get; set; }
    }
}
