//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prijava
    {
        public Prijava()
        {
            this.Student = new HashSet<Student>();
        }
    
        public int idPrijava { get; set; }
        public string imeStudenta { get; set; }
        public string priimekStudenta { get; set; }
        public string gesloStudent { get; set; }
        public string mailStudent { get; set; }
    
        public virtual ICollection<Student> Student { get; set; }
    }
}
