//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public Profesor()
        {
            this.IzvedbaPredmeta = new HashSet<IzvedbaPredmeta>();
            this.IzvedbaPredmeta1 = new HashSet<IzvedbaPredmeta>();
            this.IzvedbaPredmeta2 = new HashSet<IzvedbaPredmeta>();
        }
    
        public int idProfesor { get; set; }
        public string imeProfesorja { get; set; }
        public string priimekProfesorja { get; set; }
    
        public virtual ICollection<IzvedbaPredmeta> IzvedbaPredmeta { get; set; }
        public virtual ICollection<IzvedbaPredmeta> IzvedbaPredmeta1 { get; set; }
        public virtual ICollection<IzvedbaPredmeta> IzvedbaPredmeta2 { get; set; }
    }
}
