//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class SestavniDelPred
    {
        public SestavniDelPred()
        {
            this.PredmetStudijskegaPrograma = new HashSet<PredmetStudijskegaPrograma>();
        }
    
        public int idSestavniDelPred { get; set; }
        public string opisSestavnegaDela { get; set; }
        public Nullable<bool> jeModul { get; set; }
    
        public virtual ICollection<PredmetStudijskegaPrograma> PredmetStudijskegaPrograma { get; set; }
    }
}
