//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sklep
    {
        public int idSklep { get; set; }
        public string VsebinaSklepa { get; set; }
        public int Student_IdStudenta { get; set; }
        public int Student_idStudent { get; set; }
        public string Organ { get; set; }
        public Nullable<System.DateTime> DatumSprejetjaSklepa { get; set; }
        public Nullable<System.DateTime> DatumVeljaveSklepa { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
