//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusPrijave
    {
        public StatusPrijave()
        {
            this.PrijavaNaIzpit = new HashSet<PrijavaNaIzpit>();
        }
    
        public int idStatusPrijave { get; set; }
        public string opisStatusaPrijave { get; set; }
    
        public virtual ICollection<PrijavaNaIzpit> PrijavaNaIzpit { get; set; }
    }
}
