//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class stopnjaStudija
    {
        public stopnjaStudija()
        {
            this.Klasius = new HashSet<Klasius>();
            this.StudijskiProgram = new HashSet<StudijskiProgram>();
        }
    
        public int idStopnjaStudija { get; set; }
        public string kratica { get; set; }
        public string stopnja { get; set; }
        public string naziv { get; set; }
    
        public virtual ICollection<Klasius> Klasius { get; set; }
        public virtual ICollection<StudijskiProgram> StudijskiProgram { get; set; }
    }
}
