//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Sklep = new HashSet<Sklep>();
            this.Zeton = new HashSet<Zeton>();
            this.Vpis = new HashSet<Vpis>();
        }
    
        public int idStudent { get; set; }
        public Nullable<int> Drzava_idDrzava { get; set; }
        public Nullable<int> Posta_idPosta { get; set; }
        public Nullable<int> Drzava_idDrzavaRojstva { get; set; }
        public Nullable<int> Prijava_idPrijava { get; set; }
        public string imeStudenta { get; set; }
        public string priimekStudenta { get; set; }
        public string gesloStudenta { get; set; }
        public string mailStudenta { get; set; }
        public Nullable<int> vpisnaStudenta { get; set; }
        public Nullable<int> Vloge_idVloge { get; set; }
        public Nullable<int> Obcina_idObcina { get; set; }
        public string Naslov { get; set; }
        public string NaslovZacasni { get; set; }
        public Nullable<int> Drzava_idDrzavaZacasna { get; set; }
        public Nullable<int> Posta_idPostaZacasna { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> Obcina_idObcinaZacasna { get; set; }
        public Nullable<sbyte> VrocanjeStalnoBivalisce { get; set; }
        public string EMSO { get; set; }
        public Nullable<int> Drzava_idDrzavaDrzavljanstvo { get; set; }
        public string Spol { get; set; }
        public Nullable<long> DavcnaStevilka { get; set; }
        public Nullable<System.DateTime> DatumRojstva { get; set; }
        public string KrajRojstva { get; set; }
        public Nullable<int> Obcina_idObcinaRojstva { get; set; }
        public Nullable<int> Klasius_idKlasius { get; set; }
    
        public virtual Drzava Drzava { get; set; }
        public virtual Drzava Drzava1 { get; set; }
        public virtual Drzava Drzava2 { get; set; }
        public virtual Drzava Drzava3 { get; set; }
        public virtual Klasius Klasius { get; set; }
        public virtual Obcina Obcina { get; set; }
        public virtual Obcina Obcina1 { get; set; }
        public virtual Obcina Obcina2 { get; set; }
        public virtual Posta Posta { get; set; }
        public virtual Posta Posta1 { get; set; }
        public virtual Prijava Prijava { get; set; }
        public virtual ICollection<Sklep> Sklep { get; set; }
        public virtual ICollection<Zeton> Zeton { get; set; }
        public virtual Vloge Vloge { get; set; }
        public virtual ICollection<Vpis> Vpis { get; set; }
    }
}
