//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudijskoLeto
    {
        public StudijskoLeto()
        {
            this.IzvedbaPredmeta = new HashSet<IzvedbaPredmeta>();
        }
    
        public int idStudijskoLeto { get; set; }
        public string studijskoLeto1 { get; set; }
    
        public virtual ICollection<IzvedbaPredmeta> IzvedbaPredmeta { get; set; }
    }
}
