//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TPOZdejPaZares
{
    using System;
    using System.Collections.Generic;
    
    public partial class VpisaniPredmet
    {
        public VpisaniPredmet()
        {
            this.PrijavaNaIzpit = new HashSet<PrijavaNaIzpit>();
        }
    
        public int Vpis_idVpis { get; set; }
        public int idVpisaniPredmet { get; set; }
        public Nullable<int> ocena { get; set; }
        public Nullable<int> IzvedbaPredmeta_idIzvedbaPredmeta { get; set; }
    
        public virtual IzvedbaPredmeta IzvedbaPredmeta { get; set; }
        public virtual ICollection<PrijavaNaIzpit> PrijavaNaIzpit { get; set; }
        public virtual Vpis Vpis { get; set; }
    }
}
