SELECT 
    `Student`.`idStudent`,
    `Student`.`Prijava_idPrijava`,
    `Student`.`imeStudenta`,
    `Student`.`priimekStudenta`,
    `Student`.`gesloStudenta`,
    `Student`.`mailStudenta`,
    `Student`.`vpisnaStudenta`,
    `Student`.`Vloge_idVloge`
FROM
    `t8_2015`.`Student`;
